mongodb:
  image: mongo:4.2-bionic
  container_name: mongo-bitdb
  ports:
    - "12311:27017"
  volumes:
    - ../data/mongodb:/data/db
  command: mongod --logpath=/dev/null # -- quiet
  restart: always

slpdb:
  build: .
  dockerfile: Dockerfile
  #image: christroutner/slpdb-mainnet_slpdb:0.15.3
  container_name: bitdb
  links:
    - mongodb
  volumes:
    - ../config:/home/safeuser/config
    - ../data/leveldb:/home/safeuser/bitdb/leveldb
  restart: always

#slpserve:
#  build: ./slpserve/
#  dockerfile: Dockerfile
  #image: christroutner/slpdb-mainnet_slpserve
#  container_name: slpserve
#  links:
#    - mongodb
#  ports:
#    - "12300:4000"
#  restart: always
